package error_scenarios

main :: fn() {
    with 
        x : int = 3
    }
    loop {
        break
    }
}
